export type { Obstacle } from './obstacle'
export { createObstacle } from './obstacle'
export type { Ship, ShipColorEntry } from './ship'
export { createShip, SHIP_COLORS } from './ship'
export type { SimulationState, Vec2 } from './simulation'
export { INITIAL_SIMULATION_STATE } from './simulation'
export { Vector } from './vector'
